# config-repo/application.yml
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      # Use HTTP endpoint by default; override via env OTEL_EXPORTER_OTLP_ENDPOINT
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

# Identify service in traces
management.observations.key-values.application=${spring.application.name}

# Optional: W3C trace context is default; keep headers propagated via Spring Cloud

# Logging with trace/span ids
logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
