# config-repo/application.yml
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
