spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mariadb://localhost:3306/authdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:change-me}   # make sure poll-service uses the same value

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
