spring:
  application:
    name: poll-service
  datasource:
    url: jdbc:mariadb://localhost:3306/polldb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:change-me}   # MUST match auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
