spring:
  application:
    name: user-service

security:
  jwt:
    # Provide via environment/JVM arg in config-server environment; fallback handled in service
    secret: ${JWT_SECRET}
    issuer: polling-app-auth
