spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8765

limits:
  service:
    url: http://localhost:8084

security:
  jwt:
    secret: "L+tc2CP2cSx2R6y4D1S0rME2SLYeiq2NwqxYnhtGe0LSHNaxt4beEmQixlpQ7GoPz6+zYd2alMISFnP2ecNJSQ=="
    issuer: polling-app-auth
    secret-base64: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
