spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8765

limits:
  service:
    url: http://localhost:8082

security:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_IN_CONFIG_SERVER}
    issuer: polling-app-auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
