spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

# JWT values should live in config-repo; keep here only for local dev if needed
security:
  jwt:
    secret: mySuperStrongSecretKeyThatIsAtLeast32CharactersLong!
    issuer: polling-app-auth