apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'prometheus'
        mappedTags:
          - key: service.name
            value: job
      serviceMap:
        datasourceUid: 'prometheus'

