server:
  port: 8084

spring:
  application:
    name: limits-service
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
        prefer-ip-address: false
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}

