spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
        prefer-ip-address: false
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

security:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_IN_CONFIG_SERVER}
    issuer: polling-app-auth
    access-exp-seconds: 3600
