
# language: yaml
# File: user-service/src/main/resources/application-dev.yml
server:
  port: 8000

spring:
  application:
    name: user-service
  main:
    allow-circular-references: true
    lazy-initialization: true
  datasource:
    url: jdbc:mariadb://localhost:3307/users_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 'munji1280'
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: Africa/Kampala
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Africa/Kampala

logging:
  level:
    org.hibernate.SQL: info
  pattern:
    level: "%5p [${spring.application.name:},${X-B3-TraceId:-},${X-B3-SpanId:-}]"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
      sample-api:
        maxConcurrentCalls: 10

management:
  tracing:
    sampling:
      probability: 1.0

app:
  cors:
    allowedOrigins: "*"

security:
  jwt:
    secret: 4e96bde4beb408133e5d5cc89987be410eb71d6418c34d0f47a83c9bb0c73fd2d171c4b1b3f9503922888d557f0de47dd01ff97a68b482e8c58acda
    access-exp-seconds: 10800

