spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
        prefer-ip-address: false
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,250ms,500ms,1s,2s
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  pattern:
    level: "%5p [${spring.application.name:},trace_id=%mdc{trace_id:-},span_id=%mdc{span_id:-}]"

security:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_IN_CONFIG_SERVER}
    issuer: polling-app-auth
    access-exp-seconds: 3600
