server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          # For production, use a remote Git repository:
          # uri: https://github.com/your-org/voting-system-config
          # username: ${GIT_USERNAME}
          # password: ${GIT_PASSWORD}
          default-label: main
          clone-on-start: true
          timeout: 5
        # Enable health indicator
        health:
          enabled: true
  # Security - Basic Auth (optional, recommended for production)
  # security:
  #   user:
  #     name: config-user
  #     password: ${CONFIG_PASSWORD:changeme}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

# Logging
logging:
  level:
    root: INFO
    com.votingsystem: DEBUG
    org.springframework.cloud.config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"